Bug 40414: Update macos-signer-notarization
Update macos-signer-notarization to the version currently in use.

diff --git a/tools/signing/macos-signer-notarization b/tools/signing/macos-signer-notarization
--- a/tools/signing/macos-signer-notarization
+++ b/tools/signing/macos-signer-notarization
@@ -1,50 +1,40 @@
-#!/bin/bash
+set -e
+set -x
 
-# Copyright (c) 2019, The Tor Project, Inc.
-#
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are
-# met:
-
-#     * Redistributions of source code must retain the above copyright
-# notice, this list of conditions and the following disclaimer.
-#
-#     * Redistributions in binary form must reproduce the above
-# copyright notice, this list of conditions and the following disclaimer
-# in the documentation and/or other materials provided with the
-# distribution.
-#
-#     * Neither the names of the copyright owners nor the names of its
-# contributors may be used to endorse or promote products derived from
-# this software without specific prior written permission.
-#
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-
+ALTOOL=~/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework/Versions/A/Support/altool
 TORBROWSER_VERSION=$1
 if [ -z "$TORBROWSER_VERSION" ];
 then
   echo "Please call this script with a Tor Browser version!"
   exit 1
 fi
-BUNDLE_LOCALES="ar ca cs da de el en-US es-AR es-ES fa fr ga-IE he hu id is it ja ka ko mk nb-NO nl pl pt-BR ro ru sv-SE tr vi zh-CN zh-TW"
+if [ -z "${PW}" ]; then
+  stty -echo; read PW; stty echo; export PW
+fi
+if [ -z "$BUNDLE_LOCALES" ];
+then
+  BUNDLE_LOCALES="ar ca cs da de el en-US es-AR es-ES fa fr ga-IE he hu id is it ja ka ko lt mk ms my nb-NO nl pl pt-BR ro ru sv-SE th tr vi zh-CN zh-TW"
+fi
 for LANG in $BUNDLE_LOCALES
 do
+  if test -d ${LANG}; then
+    mv ${LANG}/tb-${TORBROWSER_VERSION}_$LANG.zip ./
+    rm -r ${LANG}/
+  fi
   mkdir $LANG
   cd $LANG
   mv ../tb-${TORBROWSER_VERSION}_$LANG.zip .
   unzip -q tb-${TORBROWSER_VERSION}_$LANG.zip
   echo "Notarizing $LANG..."
-  xcrun altool --notarize-app -t osx -f tb-${TORBROWSER_VERSION}_$LANG.zip
-  --primary-bundle-id org.torproject.torbrowser -u USERNAME -p @env:PW --output-format xml
+  #xcrun altool --notarize-app --verbose -t osx -f tb-${TORBROWSER_VERSION}_$LANG.zip --primary-bundle-id org.torproject.torbrowser -u boklm@torproject.org -p @env:PW --output-format xml | tee tb-${TORBROWSER_VERSION}_$LANG.zip.log 2>&1
+  $ALTOOL --notarize-app --verbose -t osx -f tb-${TORBROWSER_VERSION}_$LANG.zip --primary-bundle-id org.torproject.torbrowser -u boklm@torproject.org -p @env:PW --output-format xml | tee tb-${TORBROWSER_VERSION}_$LANG.zip.log 2>&1
+
+  request_uuid=`grep -A1 RequestUUID tb-${TORBROWSER_VERSION}_$LANG.zip.log | grep -o '[0-9a-f]\+[0-9a-f-]\+'`
+  if [ -z "${request_uuid}" ]; then
+    echo "Request UUID not present. Notarization failed"
+    exit 1
+  fi
+  echo ${request_uuid} > tb-${TORBROWSER_VERSION}_$LANG.zip.uuid
+
   cd ..
 done
