Bug 41168: Check that we are not changing other channel when deploying update_responses

diff --git a/tools/signing/upload-update_responses-to-staticiforme b/tools/signing/upload-update_responses-to-staticiforme
--- a/tools/signing/upload-update_responses-to-staticiforme
+++ b/tools/signing/upload-update_responses-to-staticiforme
@@ -63,6 +63,18 @@ echo "update_responses_commit: $update_responses_commit"
 
 cd "$update_dir"
 git fetch
+changed_files="\$(git diff --name-only HEAD $update_responses_commit)"
+if ! echo "\$changed_files" | grep -qv "$tbb_version_type"
+then
+  echo >&2 "Error: checking out new update_response_commit will changes"
+  echo >&2 "some files outside of the $tbb_version_type directory:"
+  echo "\$changed_files" | grep -v "$tbb_version_type" >&2
+  echo >&2 "--"
+  echo >&2 "If this is really what you want to do, edit this script to"
+  echo >&2 "remove the line 'exit 1' and run it again."
+  echo >&2 "See tor-browser-build#41168 for more details."
+  exit 1
+fi
 git checkout "$update_responses_commit"
 
 static-update-component aus1.torproject.org
